In [32]:
#Import Packages
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split #train_test_split helps split data into train & test set 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn import tree 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score, recall_score
from sklearn.model_selection import GridSearchCV #Import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [33]:
#Import training dataset
balance_data = pd.read_csv( 
'C:\\Users\\HP\\Desktop\\coursework ml\\CE802_Ass_2019_Data.csv',sep= ',') 
#import test dataset
pred_data=pd.read_csv( 
'C:\\Users\\HP\\Desktop\\coursework ml\\CE802_Ass_2019_Test.csv',sep= ',') 
#import dataset by removing 20th column with nan values
#cols = list(pd.read_csv('C:\\Users\\HP\\Desktop\\coursework ml\\CE802_Ass_2019_Data.csv', nrows =1))
#balance_data = pd.read_csv( 
#'C:\\Users\\HP\\Desktop\\coursework ml\\CE802_Ass_2019_Data.csv',usecols =[i for i in cols if i != 'F20'],sep= ',') 
#pred_data=pd.read_csv( 
#'C:\\Users\\HP\\Desktop\\coursework ml\\CE802_Ass_2019_Test.csv',usecols =[i for i in cols if i != 'F20'],sep= ',') 

In [34]:
#missing values in training dataset
balance_data['F20'].fillna(balance_data['F20'].mean())
balance_data=balance_data.fillna(balance_data.mean())


#missing values in test dataset
pred_data['F20'].fillna(pred_data['F20'].mean())
pred_data=pred_data.fillna(pred_data.mean())

#dataset shape
print("Length: ", len(balance_data)) 
print("Dataset Shape: ", balance_data.shape)

#dataset observation
balance_data.head()

Length:  500
Dataset Shape:  (500, 21)


F1  F2   F3    F4    F5    F6    F7    F8   F9  F10  ...   F12   F13  F14  \
0   0   0   16  2.02  0.52 -2.35 -1.98 -0.70   85    6  ... -0.07  1.08   15   
1   0   0   86 -0.90  2.75  0.14  0.83 -0.06  107    1  ...  0.17  1.06   -8   
2   1   1  165  0.73  1.05  0.10  2.57 -1.65   41    5  ...  0.04  0.42   -6   
3   1   1  191 -1.50  0.79  0.33  1.24  1.35   17    2  ...  1.74  1.74   15   
4   1   1   13  0.25 -1.19 -0.90  2.67  0.22   12    8  ... -0.39  1.25   25   

    F15   F16   F17   F18   F19       F20  Class  
0 -0.63 -3.49 -1.68  0.02  15.3  0.074146   True  
1 -1.21  0.34  0.36  0.61  10.1  0.074146   True  
2 -0.46 -0.62  1.67  2.60  11.0  1.550000  False  
3  0.47  0.63  0.08  0.19   6.3  0.950000  False  
4 -0.09 -2.41 -0.53 -0.77  10.5  0.074146   True  

[5 rows x 21 columns]

In [35]:
#data slicing 
X = balance_data.values[:,:-1]
Y = balance_data.values[:,20]

#cutomized code to convert response variable in 0 and 1 for the use in algorithm
for i in range (Y.size):
    if Y[i]:
        Y[i] = 1
    else:
        Y[i] = 0
Y=Y.astype(int)

X_pred=pred_data.values[:,0:20]

#split the dataset into 70% training and 30% testing set 
X_train, X_validate, y_train, y_test = train_test_split( X, Y, test_size = 0.3, random_state = 100)

In [36]:
######Decision tree pruning #########
#Creating decision tree classifier object with gini index
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 0, 
                               max_depth=3, min_samples_leaf=5)
#Perform Training
clf_gini.fit(X_train, y_train)

#Pridiction on test set with gini index
y_pred = clf_gini.predict(X_validate)
#print(y_pred)

#Calculating Test set Accuracy with gini index
print("Confusion Matrix:\n ",confusion_matrix(y_test, y_pred))  
print ("Accuracy : ",accuracy_score(y_test,y_pred)*100)  
print("Precision:",metrics.precision_score(y_test, y_pred)*100) 
print("Recall:",metrics.recall_score(y_test, y_pred)*100)
print("Report : \n",classification_report(y_test, y_pred)) 


Confusion Matrix:
  [[70 11]
 [55 14]]
Accuracy :  56.00000000000001
Precision: 56.00000000000001
Recall: 20.28985507246377
Report : 
               precision    recall  f1-score   support

           0       0.56      0.86      0.68        81
           1       0.56      0.20      0.30        69

    accuracy                           0.56       150
   macro avg       0.56      0.53      0.49       150
weighted avg       0.56      0.56      0.50       150



In [37]:
#Creating decision tree classifier object with information gain 
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100, 
 max_depth=3, min_samples_leaf=5) 

#Perform Training
clf_entropy.fit(X_train, y_train) 

#Pridiction on test set with information gain 
y_pred_en = clf_entropy.predict(X_validate)
#print(y_pred_en)

#Calculating Test set Accuracy with information gain 
print("Confusion Matrix: \n ",  
      confusion_matrix(y_test,y_pred_en))
print("Accuracy: ", accuracy_score(y_test,y_pred_en)*100) 
print("Precision:",metrics.precision_score(y_test, y_pred_en)*100) 
print("Recall:",metrics.recall_score(y_test, y_pred_en)*100)
print("Report :\n ",classification_report(y_test,y_pred_en)) 

Confusion Matrix: 
  [[70 11]
 [53 16]]
Accuracy:  57.333333333333336
Precision: 59.25925925925925
Recall: 23.18840579710145
Report :
                precision    recall  f1-score   support

           0       0.57      0.86      0.69        81
           1       0.59      0.23      0.33        69

    accuracy                           0.57       150
   macro avg       0.58      0.55      0.51       150
weighted avg       0.58      0.57      0.52       150



In [38]:
#Results of both criteria are nearly same
#Difficult to choose which is better
from sklearn.metrics import precision_score, recall_score
#print hyperparameters  
print(clf_gini.get_params()) 

#pruning with Grid search CV 
#Defining grid of hyperparameters 
parameter_grid = { 
'max_depth': [1,3,5,7,9,20], 
'min_samples_split': [2,3, 4, 5], 
'min_impurity_decrease': [0.01 , 0.012,0.004 , 0.008], 
'min_samples_leaf':[2,5,6,8,10] 
}

# Instantiate a 10-fold CV grid search object 'grid' 
grid = GridSearchCV(estimator=clf_gini, 
                       param_grid=parameter_grid, 
                       scoring='accuracy', 
                       cv=10) 
# Fit grid to the training set. 
grid.fit(X_train, y_train) 

# Best CV score across all parameters from 'grid' 
print('Best CV accuracy: ',format(grid.best_score_*100))

#Best hyperparameters   
print('Best hyerparameters: ', grid.best_params_ )


#Best Estimator
best_model = grid.best_estimator_ 
# Calculate accuracy 
print("Accuracy of best model ",format(best_model.score(X_validate,y_test)*100))
#Accuracy is same as entropy criterion.So,precision and recall is same as information gain

{'class_weight': None, 'criterion': 'gini', 'max_depth': 3, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 5, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'presort': False, 'random_state': 0, 'splitter': 'best'}
Best CV accuracy:  59.14285714285714
Best hyerparameters:  {'max_depth': 3, 'min_impurity_decrease': 0.01, 'min_samples_leaf': 5, 'min_samples_split': 2}
Accuracy of best model  57.333333333333336


In [39]:
#Logistic Regression Classification 
#import required libraries 
from sklearn.linear_model import LogisticRegression 
import warnings 
warnings.filterwarnings("ignore", category=FutureWarning) 
from sklearn import metrics # import the metrics class 

# instantiate the model
logreg = LogisticRegression() 
# fit the model with training data 
logreg.fit(X_train,y_train) 
#predicting with test set 
y_pred_reg=logreg.predict(X_validate) 

# comparing actual response values (y_test) with predicted response values (y_pred) 
print("Confusion Matrix: \n ",confusion_matrix(y_test,y_pred_reg))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_reg)*100) 
print("Precision:",metrics.precision_score(y_test, y_pred_reg)*100) 
print("Recall:",metrics.recall_score(y_test, y_pred_reg)*100)

Confusion Matrix: 
  [[63 18]
 [37 32]]
Accuracy: 63.33333333333333
Precision: 64.0
Recall: 46.3768115942029


In [40]:
# import support vector classifier 
from sklearn.svm import SVC # "Support Vector Classifier" 
supp_vector = SVC(kernel='linear')
# instantiate the model (using the default parameters)  
# fit the model with data 
supp_vector.fit(X_train,y_train) 
#predicting with test set 
y_pred_svc=supp_vector.predict(X_validate) 

# comparing actual response values (y_test) with predicted response values (y_pred) 
print("Confusion Matrix: \n ",confusion_matrix(y_test,y_pred_svc))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_svc)*100) 
print("Precision:",metrics.precision_score(y_test, y_pred_svc)*100) 
print("Recall:",metrics.recall_score(y_test, y_pred_svc)*100)

Confusion Matrix: 
  [[68 13]
 [39 30]]
Accuracy: 65.33333333333333
Precision: 69.76744186046511
Recall: 43.47826086956522


In [41]:
#Naive Bayes Classification
# training the model on training set

#import library
from sklearn.naive_bayes import GaussianNB
#This library already included in the beginning
from sklearn import metrics 

#instantiate the model
gnb = GaussianNB() 

#fit the model with data 
gnb.fit(X_train,y_train) 
  
# making predictions on the testing set 
y_pred_bayes = gnb.predict(X_validate) 
  
# comparing actual response values (y_test) with predicted response values (y_pred) 
print("Confusion Matrix: \n ",confusion_matrix(y_test,y_pred_bayes))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_bayes)*100) 
print("Precision:",metrics.precision_score(y_test, y_pred_bayes)*100) 
print("Recall:",metrics.recall_score(y_test, y_pred_bayes)*100)

Confusion Matrix: 
  [[62 19]
 [47 22]]
Accuracy: 56.00000000000001
Precision: 53.65853658536586
Recall: 31.88405797101449


In [42]:
#Support Vector is the best algorithm among four.
best_y_pred=supp_vector.predict(X_pred)

#Converting class integer values into boolean values
a=0
b=0
for i in best_y_pred: 
    if i==0: 
        best_y_pred[i] = True 
        a=a+1
    else: 
        best_y_pred[i] = False
        b=b+1
best_y_pred = best_y_pred.astype(bool)

#Printing total number of '0' and '1' in predicted outcome
print("0: ",a) 
print("1: ",b)       

#fill the predicted results in test csv.
#import the test dataset
#fill the predicted class in test dataset
pred_data['Class'] = best_y_pred
pred_data['Class'] = pred_data['Class']

#Form csv file of predicted results
pred_data.to_csv('C:\\Users\\HP\\Desktop\\coursework ml\\New folder\\New_Version_CE802_Ass_2019_Test.csv')

0:  359
1:  141


In [44]:
"""Coding help taken from these websites
Decision tree:
https://www.geeksforgeeks.org/decision-tree-implementation-python/
https://www.ritchieng.com/machine-learning-decision-trees/

Logistic Regression:
https://www.datacamp.com/community/tutorials/understanding-logistic-regression-python

Support Vector:
https://www.geeksforgeeks.org/classifying-data-using-support-vector-machinessvms-in-python/

Naive Bayes:
https://www.datacamp.com/community/tutorials/naive-bayes-scikit-learn

Missing value:
https://jamesrledoux.com/code/imputation

CSV:https:
//stackoverflow.com/questions/34864695/saving-prediction-results-to-csv """

'Coding help taken from these websites\nDecision tree:\nhttps://www.geeksforgeeks.org/decision-tree-implementation-python/\nhttps://www.ritchieng.com/machine-learning-decision-trees/\n\nLogistic Regression:\nhttps://www.datacamp.com/community/tutorials/understanding-logistic-regression-python\n\nSupport Vector:\nhttps://www.geeksforgeeks.org/classifying-data-using-support-vector-machinessvms-in-python/\n\nNaive Bayes:\nhttps://www.datacamp.com/community/tutorials/naive-bayes-scikit-learn\n\nMissing value:\nhttps://jamesrledoux.com/code/imputation\n\nCSV:https:\n//stackoverflow.com/questions/34864695/saving-prediction-results-to-csv '